package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private Integer adminid;
     private User user;
     private String firstName;
     private String lastName;
     private String officeTelephone;
     private String mobileNumber;
     private String emaillAddress;

    public Admin() {
    }

    public Admin(User user, String firstName, String lastName, String officeTelephone, String mobileNumber, String emaillAddress) {
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.officeTelephone = officeTelephone;
       this.mobileNumber = mobileNumber;
       this.emaillAddress = emaillAddress;
    }
   
    public Integer getAdminid() {
        return this.adminid;
    }
    
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getOfficeTelephone() {
        return this.officeTelephone;
    }
    
    public void setOfficeTelephone(String officeTelephone) {
        this.officeTelephone = officeTelephone;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmaillAddress() {
        return this.emaillAddress;
    }
    
    public void setEmaillAddress(String emaillAddress) {
        this.emaillAddress = emaillAddress;
    }




}


