package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * HotelOfficer generated by hbm2java
 */
public class HotelOfficer  implements java.io.Serializable {


     private Integer hotelOfficerId;
     private User user;
     private Hotel hotel;
     private String firstName;
     private String lastName;
     private String officeTelephone;
     private String mobileNumber;
     private String emailAddress;

    public HotelOfficer() {
    }

	
    public HotelOfficer(User user, Hotel hotel) {
        this.user = user;
        this.hotel = hotel;
    }
    public HotelOfficer(User user, Hotel hotel, String firstName, String lastName, String officeTelephone, String mobileNumber, String emailAddress) {
       this.user = user;
       this.hotel = hotel;
       this.firstName = firstName;
       this.lastName = lastName;
       this.officeTelephone = officeTelephone;
       this.mobileNumber = mobileNumber;
       this.emailAddress = emailAddress;
    }
   
    public Integer getHotelOfficerId() {
        return this.hotelOfficerId;
    }
    
    public void setHotelOfficerId(Integer hotelOfficerId) {
        this.hotelOfficerId = hotelOfficerId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getOfficeTelephone() {
        return this.officeTelephone;
    }
    
    public void setOfficeTelephone(String officeTelephone) {
        this.officeTelephone = officeTelephone;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }




}


