package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * HotelImage generated by hbm2java
 */
public class HotelImage  implements java.io.Serializable {


     private HotelImageId id;
     private Hotel hotel;
     private String imageUrl;
     private String imageSize;
     private String imageType;

    public HotelImage() {
    }

	
    public HotelImage(HotelImageId id, Hotel hotel) {
        this.id = id;
        this.hotel = hotel;
    }
    public HotelImage(HotelImageId id, Hotel hotel, String imageUrl, String imageSize, String imageType) {
       this.id = id;
       this.hotel = hotel;
       this.imageUrl = imageUrl;
       this.imageSize = imageSize;
       this.imageType = imageType;
    }
   
    public HotelImageId getId() {
        return this.id;
    }
    
    public void setId(HotelImageId id) {
        this.id = id;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getImageSize() {
        return this.imageSize;
    }
    
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize;
    }
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }




}


