package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer hotelId;
     private String hotelName;
     private String hotelAddress;
     private String emailAddress;
     private Byte hotelStatus;
     private String hotelDescription;
     private String enteredBy;
     private Date enteredDate;
     private Set hotelImages = new HashSet(0);
     private Set hotelTypes = new HashSet(0);
     private Set hotelOfficers = new HashSet(0);
     private Set locations = new HashSet(0);
     private Set cityDetails = new HashSet(0);
     private Set hotelContacts = new HashSet(0);

    public Hotel() {
    }

    public Hotel(String hotelName, String hotelAddress, String emailAddress, Byte hotelStatus, String hotelDescription, String enteredBy, Date enteredDate, Set hotelImages, Set hotelTypes, Set hotelOfficers, Set locations, Set cityDetails, Set hotelContacts) {
       this.hotelName = hotelName;
       this.hotelAddress = hotelAddress;
       this.emailAddress = emailAddress;
       this.hotelStatus = hotelStatus;
       this.hotelDescription = hotelDescription;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.hotelImages = hotelImages;
       this.hotelTypes = hotelTypes;
       this.hotelOfficers = hotelOfficers;
       this.locations = locations;
       this.cityDetails = cityDetails;
       this.hotelContacts = hotelContacts;
    }
   
    public Integer getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }
    public String getHotelAddress() {
        return this.hotelAddress;
    }
    
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public Byte getHotelStatus() {
        return this.hotelStatus;
    }
    
    public void setHotelStatus(Byte hotelStatus) {
        this.hotelStatus = hotelStatus;
    }
    public String getHotelDescription() {
        return this.hotelDescription;
    }
    
    public void setHotelDescription(String hotelDescription) {
        this.hotelDescription = hotelDescription;
    }
    public String getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(String enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getHotelImages() {
        return this.hotelImages;
    }
    
    public void setHotelImages(Set hotelImages) {
        this.hotelImages = hotelImages;
    }
    public Set getHotelTypes() {
        return this.hotelTypes;
    }
    
    public void setHotelTypes(Set hotelTypes) {
        this.hotelTypes = hotelTypes;
    }
    public Set getHotelOfficers() {
        return this.hotelOfficers;
    }
    
    public void setHotelOfficers(Set hotelOfficers) {
        this.hotelOfficers = hotelOfficers;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }
    public Set getCityDetails() {
        return this.cityDetails;
    }
    
    public void setCityDetails(Set cityDetails) {
        this.cityDetails = cityDetails;
    }
    public Set getHotelContacts() {
        return this.hotelContacts;
    }
    
    public void setHotelContacts(Set hotelContacts) {
        this.hotelContacts = hotelContacts;
    }




}


