package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * HotelType generated by hbm2java
 */
public class HotelType  implements java.io.Serializable {


     private Integer hotelTypeId;
     private String typeName;
     private Byte hotelTypeStatus;
     private Set hotels = new HashSet(0);

    public HotelType() {
    }

    public HotelType(String typeName, Byte hotelTypeStatus, Set hotels) {
       this.typeName = typeName;
       this.hotelTypeStatus = hotelTypeStatus;
       this.hotels = hotels;
    }
   
    public Integer getHotelTypeId() {
        return this.hotelTypeId;
    }
    
    public void setHotelTypeId(Integer hotelTypeId) {
        this.hotelTypeId = hotelTypeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Byte getHotelTypeStatus() {
        return this.hotelTypeStatus;
    }
    
    public void setHotelTypeStatus(Byte hotelTypeStatus) {
        this.hotelTypeStatus = hotelTypeStatus;
    }
    public Set getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set hotels) {
        this.hotels = hotels;
    }




}


