package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * HotelContact generated by hbm2java
 */
public class HotelContact  implements java.io.Serializable {


     private HotelContactId id;
     private Hotel hotel;
     private String contactType;

    public HotelContact() {
    }

	
    public HotelContact(HotelContactId id, Hotel hotel) {
        this.id = id;
        this.hotel = hotel;
    }
    public HotelContact(HotelContactId id, Hotel hotel, String contactType) {
       this.id = id;
       this.hotel = hotel;
       this.contactType = contactType;
    }
   
    public HotelContactId getId() {
        return this.id;
    }
    
    public void setId(HotelContactId id) {
        this.id = id;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public String getContactType() {
        return this.contactType;
    }
    
    public void setContactType(String contactType) {
        this.contactType = contactType;
    }




}


