package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * HotelContactId generated by hbm2java
 */
public class HotelContactId  implements java.io.Serializable {


     private int hotelId;
     private String contactNumber;

    public HotelContactId() {
    }

    public HotelContactId(int hotelId, String contactNumber) {
       this.hotelId = hotelId;
       this.contactNumber = contactNumber;
    }
   
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HotelContactId) ) return false;
		 HotelContactId castOther = ( HotelContactId ) other; 
         
		 return (this.getHotelId()==castOther.getHotelId())
 && ( (this.getContactNumber()==castOther.getContactNumber()) || ( this.getContactNumber()!=null && castOther.getContactNumber()!=null && this.getContactNumber().equals(castOther.getContactNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHotelId();
         result = 37 * result + ( getContactNumber() == null ? 0 : this.getContactNumber().hashCode() );
         return result;
   }   


}


