package com.duminda.ceylonjourney.model;
// Generated Feb 22, 2013 2:25:23 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * HotelContract generated by hbm2java
 */
public class HotelContract  implements java.io.Serializable {


     private int hotelId;
     private Date startDate;
     private Date endDate;
     private Date enteredDate;

    public HotelContract() {
    }

    public HotelContract(int hotelId, Date startDate, Date endDate, Date enteredDate) {
       this.hotelId = hotelId;
       this.startDate = startDate;
       this.endDate = endDate;
       this.enteredDate = enteredDate;
    }
   
    public int getHotelId() {
        return this.hotelId;
    }
    
    public void setHotelId(int hotelId) {
        this.hotelId = hotelId;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }




}


