package com.duminda.ceylonjourney.model;
// Generated Feb 20, 2013 12:36:53 PM by Hibernate Tools 3.2.1.GA



/**
 * HotLocation generated by hbm2java
 */
public class HotLocation  implements java.io.Serializable {


     private int locationId;

    public HotLocation() {
    }

    public HotLocation(int locationId) {
       this.locationId = locationId;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }




}


