package com.duminda.ceylonjourney.model;
// Generated Feb 24, 2013 11:55:40 PM by Hibernate Tools 3.2.1.GA



/**
 * InternalOfficer generated by hbm2java
 */
public class InternalOfficer  implements java.io.Serializable {


     private Integer internalOfficerId;
     private User user;
     private String firstName;
     private String lastName;
     private String officeTelephone;
     private String mobileNumber;
     private String emailAddress;

    public InternalOfficer() {
    }

	
    public InternalOfficer(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public InternalOfficer(User user, String firstName, String lastName, String officeTelephone, String mobileNumber, String emailAddress) {
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.officeTelephone = officeTelephone;
       this.mobileNumber = mobileNumber;
       this.emailAddress = emailAddress;
    }
   
    public Integer getInternalOfficerId() {
        return this.internalOfficerId;
    }
    
    public void setInternalOfficerId(Integer internalOfficerId) {
        this.internalOfficerId = internalOfficerId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getOfficeTelephone() {
        return this.officeTelephone;
    }
    
    public void setOfficeTelephone(String officeTelephone) {
        this.officeTelephone = officeTelephone;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }




}


