package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * LocationSearchTypeId generated by hbm2java
 */
public class LocationSearchTypeId  implements java.io.Serializable {


     private int locationId;
     private int searchTypeId;

    public LocationSearchTypeId() {
    }

    public LocationSearchTypeId(int locationId, int searchTypeId) {
       this.locationId = locationId;
       this.searchTypeId = searchTypeId;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public int getSearchTypeId() {
        return this.searchTypeId;
    }
    
    public void setSearchTypeId(int searchTypeId) {
        this.searchTypeId = searchTypeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LocationSearchTypeId) ) return false;
		 LocationSearchTypeId castOther = ( LocationSearchTypeId ) other; 
         
		 return (this.getLocationId()==castOther.getLocationId())
 && (this.getSearchTypeId()==castOther.getSearchTypeId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLocationId();
         result = 37 * result + this.getSearchTypeId();
         return result;
   }   


}


