package com.duminda.ceylonjourney.model;
// Generated Feb 22, 2013 12:48:25 PM by Hibernate Tools 3.2.1.GA



/**
 * LocationComment generated by hbm2java
 */
public class LocationComment  implements java.io.Serializable {


     private Integer commentId;
     private int locationId;
     private String comment;
     private int commentStatus;

    public LocationComment() {
    }

    public LocationComment(int locationId, String comment, int commentStatus) {
       this.locationId = locationId;
       this.comment = comment;
       this.commentStatus = commentStatus;
    }
   
    public Integer getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public int getCommentStatus() {
        return this.commentStatus;
    }
    
    public void setCommentStatus(int commentStatus) {
        this.commentStatus = commentStatus;
    }




}


