package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private Integer locationId;
     private String locationName;
     private String locationDescription;
     private String locationAddress;
     private Byte locationStatus;
     private String welcomeImageName;
     private String welcomeImageUrl;
     private String enteredBy;
     private Date enteredDate;
     private Set locationSummaries = new HashSet(0);
     private Set searchKeywords = new HashSet(0);
     private Set hotels = new HashSet(0);
     private Set cityDetails = new HashSet(0);
     private Set locationSearchTypes = new HashSet(0);
     private Integer numberOfVotes;
     
    public Location() {
    }

	
    public Location(String locationName) {
        this.locationName = locationName;
    }
    public Location(String locationName, String locationDescription, String locationAddress, Byte locationStatus, String welcomeImageName, String welcomeImageUrl, String enteredBy, Date enteredDate, Set locationSummaries, Set searchKeywords, Set hotels, Set cityDetails, Set locationSearchTypes,Integer numberOfVotes) {
       this.locationName = locationName;
       this.locationDescription = locationDescription;
       this.locationAddress = locationAddress;
       this.locationStatus = locationStatus;
       this.welcomeImageName = welcomeImageName;
       this.welcomeImageUrl = welcomeImageUrl;
       this.enteredBy = enteredBy;
       this.enteredDate = enteredDate;
       this.locationSummaries = locationSummaries;
       this.searchKeywords = searchKeywords;
       this.hotels = hotels;
       this.cityDetails = cityDetails;
       this.locationSearchTypes = locationSearchTypes;
       this.numberOfVotes = numberOfVotes;
    }
   
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }
    public String getLocationDescription() {
        return this.locationDescription;
    }
    
    public void setLocationDescription(String locationDescription) {
        this.locationDescription = locationDescription;
    }
    public String getLocationAddress() {
        return this.locationAddress;
    }
    
    public void setLocationAddress(String locationAddress) {
        this.locationAddress = locationAddress;
    }
    public Byte getLocationStatus() {
        return this.locationStatus;
    }
    
    public void setLocationStatus(Byte locationStatus) {
        this.locationStatus = locationStatus;
    }
    public String getWelcomeImageName() {
        return this.welcomeImageName;
    }
    
    public void setWelcomeImageName(String welcomeImageName) {
        this.welcomeImageName = welcomeImageName;
    }
    public String getWelcomeImageUrl() {
        return this.welcomeImageUrl;
    }
    
    public void setWelcomeImageUrl(String welcomeImageUrl) {
        this.welcomeImageUrl = welcomeImageUrl;
    }
    public String getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(String enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEnteredDate() {
        return this.enteredDate;
    }
    
    public void setEnteredDate(Date enteredDate) {
        this.enteredDate = enteredDate;
    }
    public Set getLocationSummaries() {
        return this.locationSummaries;
    }
    
    public void setLocationSummaries(Set locationSummaries) {
        this.locationSummaries = locationSummaries;
    }
    public Set getSearchKeywords() {
        return this.searchKeywords;
    }
    
    public void setSearchKeywords(Set searchKeywords) {
        this.searchKeywords = searchKeywords;
    }
    public Set getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set hotels) {
        this.hotels = hotels;
    }
    public Set getCityDetails() {
        return this.cityDetails;
    }
    
    public void setCityDetails(Set cityDetails) {
        this.cityDetails = cityDetails;
    }
    public Set getLocationSearchTypes() {
        return this.locationSearchTypes;
    }
    
    public void setLocationSearchTypes(Set locationSearchTypes) {
        this.locationSearchTypes = locationSearchTypes;
    }

    public void setNumberOfVotes(Integer numberOfVotes){
        this.numberOfVotes = numberOfVotes;
    }

    public Integer getNumberOfVotes(){
        return this.numberOfVotes;
    }
}


