package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * LocationSummary generated by hbm2java
 */
public class LocationSummary  implements java.io.Serializable {


     private int locationId;
     private Location location;
     private String locationIntroducedBy;
     private String locationApprovedBy;

    public LocationSummary() {
    }

	
    public LocationSummary(int locationId, Location location) {
        this.locationId = locationId;
        this.location = location;
    }
    public LocationSummary(int locationId, Location location, String locationIntroducedBy, String locationApprovedBy) {
       this.locationId = locationId;
       this.location = location;
       this.locationIntroducedBy = locationIntroducedBy;
       this.locationApprovedBy = locationApprovedBy;
    }
   
    public int getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(int locationId) {
        this.locationId = locationId;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public String getLocationIntroducedBy() {
        return this.locationIntroducedBy;
    }
    
    public void setLocationIntroducedBy(String locationIntroducedBy) {
        this.locationIntroducedBy = locationIntroducedBy;
    }
    public String getLocationApprovedBy() {
        return this.locationApprovedBy;
    }
    
    public void setLocationApprovedBy(String locationApprovedBy) {
        this.locationApprovedBy = locationApprovedBy;
    }




}


