package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * LocationSearchType generated by hbm2java
 */
public class LocationSearchType  implements java.io.Serializable {


     private LocationSearchTypeId id;
     private SearchType searchType;
     private Location location;
     private Byte locationTypeStatus;

    public LocationSearchType() {
    }

	
    public LocationSearchType(LocationSearchTypeId id, SearchType searchType, Location location) {
        this.id = id;
        this.searchType = searchType;
        this.location = location;
    }
    public LocationSearchType(LocationSearchTypeId id, SearchType searchType, Location location, Byte locationTypeStatus) {
       this.id = id;
       this.searchType = searchType;
       this.location = location;
       this.locationTypeStatus = locationTypeStatus;
    }
   
    public LocationSearchTypeId getId() {
        return this.id;
    }
    
    public void setId(LocationSearchTypeId id) {
        this.id = id;
    }
    public SearchType getSearchType() {
        return this.searchType;
    }
    
    public void setSearchType(SearchType searchType) {
        this.searchType = searchType;
    }
    public Location getLocation() {
        return this.location;
    }
    
    public void setLocation(Location location) {
        this.location = location;
    }
    public Byte getLocationTypeStatus() {
        return this.locationTypeStatus;
    }
    
    public void setLocationTypeStatus(Byte locationTypeStatus) {
        this.locationTypeStatus = locationTypeStatus;
    }




}


