package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * LocationImage generated by hbm2java
 */
public class LocationImage  implements java.io.Serializable {


     private LocationImageId id;
     private String imageUrl;
     private String imageType;
     private String imageSize;

    public LocationImage() {
    }

	
    public LocationImage(LocationImageId id) {
        this.id = id;
    }
    public LocationImage(LocationImageId id, String imageUrl, String imageType, String imageSize) {
       this.id = id;
       this.imageUrl = imageUrl;
       this.imageType = imageType;
       this.imageSize = imageSize;
    }
   
    public LocationImageId getId() {
        return this.id;
    }
    
    public void setId(LocationImageId id) {
        this.id = id;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }
    public String getImageSize() {
        return this.imageSize;
    }
    
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize;
    }




}


