package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer memberId;
     private User user;
     private String firstName;
     private String lastName;
     private String emailAddress;
     private String officeTelephone;
     private String mobileNuermb;

    public Member() {
    }

	
    public Member(User user, String mobileNuermb) {
        this.user = user;
        this.mobileNuermb = mobileNuermb;
    }
    public Member(User user, String firstName, String lastName, String emailAddress, String officeTelephone, String mobileNuermb) {
       this.user = user;
       this.firstName = firstName;
       this.lastName = lastName;
       this.emailAddress = emailAddress;
       this.officeTelephone = officeTelephone;
       this.mobileNuermb = mobileNuermb;
    }
   
    public Integer getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public String getOfficeTelephone() {
        return this.officeTelephone;
    }
    
    public void setOfficeTelephone(String officeTelephone) {
        this.officeTelephone = officeTelephone;
    }
    public String getMobileNuermb() {
        return this.mobileNuermb;
    }
    
    public void setMobileNuermb(String mobileNuermb) {
        this.mobileNuermb = mobileNuermb;
    }




}


