package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SearchKeyword generated by hbm2java
 */
public class SearchKeyword  implements java.io.Serializable {


     private Integer keywordId;
     private String keywordName;
     private String keywordDescription;
     private String keywordType;
     private Set locations = new HashSet(0);

    public SearchKeyword() {
    }

    public SearchKeyword(String keywordName, String keywordDescription, String keywordType, Set locations) {
       this.keywordName = keywordName;
       this.keywordDescription = keywordDescription;
       this.keywordType = keywordType;
       this.locations = locations;
    }
   
    public Integer getKeywordId() {
        return this.keywordId;
    }
    
    public void setKeywordId(Integer keywordId) {
        this.keywordId = keywordId;
    }
    public String getKeywordName() {
        return this.keywordName;
    }
    
    public void setKeywordName(String keywordName) {
        this.keywordName = keywordName;
    }
    public String getKeywordDescription() {
        return this.keywordDescription;
    }
    
    public void setKeywordDescription(String keywordDescription) {
        this.keywordDescription = keywordDescription;
    }
    public String getKeywordType() {
        return this.keywordType;
    }
    
    public void setKeywordType(String keywordType) {
        this.keywordType = keywordType;
    }
    public Set getLocations() {
        return this.locations;
    }
    
    public void setLocations(Set locations) {
        this.locations = locations;
    }




}


