package com.duminda.ceylonjourney.model;
// Generated Feb 8, 2013 12:10:38 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private UserType userType;
     private String password;
     private Boolean userStatus;
     private Set members = new HashSet(0);
     private Set internalOfficers = new HashSet(0);
     private Set hotelOfficers = new HashSet(0);
     private Set admins = new HashSet(0);
     private transient String loginStatus;

    public User() {
    }

	
    public User(String username, UserType userType) {
        this.username = username;
        this.userType = userType;
    }
    public User(String username, UserType userType, String password, Boolean userStatus, Set members, Set internalOfficers, Set hotelOfficers, Set admins) {
       this.username = username;
       this.userType = userType;
       this.password = password;
       this.userStatus = userStatus;
       this.members = members;
       this.internalOfficers = internalOfficers;
       this.hotelOfficers = hotelOfficers;
       this.admins = admins;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public UserType getUserType() {
        return this.userType;
    }
    
    public void setUserType(UserType userType) {
        this.userType = userType;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(Boolean userStatus) {
        this.userStatus = userStatus;
    }
    public Set getMembers() {
        return this.members;
    }
    
    public void setMembers(Set members) {
        this.members = members;
    }
    public Set getInternalOfficers() {
        return this.internalOfficers;
    }
    
    public void setInternalOfficers(Set internalOfficers) {
        this.internalOfficers = internalOfficers;
    }
    public Set getHotelOfficers() {
        return this.hotelOfficers;
    }
    
    public void setHotelOfficers(Set hotelOfficers) {
        this.hotelOfficers = hotelOfficers;
    }
    public Set getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set admins) {
        this.admins = admins;
    }

    /**
     * @return the loginStatus
     */
    public String getLoginStatus() {
        return loginStatus;
    }

    /**
     * @param loginStatus the loginStatus to set
     */
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }




}


