package com.duminda.ceylonjourney.model;
// Generated Feb 24, 2013 11:55:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserType generated by hbm2java
 */
public class UserType  implements java.io.Serializable {


     private Integer userTypeId;
     private String typeName;
     private Byte loginTypeStatus;
     private Set users = new HashSet(0);

    public UserType() {
    }

    public UserType(String typeName, Byte loginTypeStatus, Set users) {
       this.typeName = typeName;
       this.loginTypeStatus = loginTypeStatus;
       this.users = users;
    }
   
    public Integer getUserTypeId() {
        return this.userTypeId;
    }
    
    public void setUserTypeId(Integer userTypeId) {
        this.userTypeId = userTypeId;
    }
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
    public Byte getLoginTypeStatus() {
        return this.loginTypeStatus;
    }
    
    public void setLoginTypeStatus(Byte loginTypeStatus) {
        this.loginTypeStatus = loginTypeStatus;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


